### ISSUE TITLE
8Bitdo Zero 2 more problems with D-pad

### ISSUE THREAD

**Issue by x51mon** [roxgib/anki-contanki#72]
Related to #63 but I think the problem and cause are somewhat different therefore a new issue.

I have a 8Bitdo Zero **2** (note the two) and did not get the D-pad to work properly, although I've set the axis roles to 'Buttons' in the options. It was in xmode and the D-pad was set to left analog stick when I tried it. Maybe the numbering of the axis change? On https://hardwaretester.com/gamepad the left/right is shown as axis 0 and up/down as axis 1

On the Zero 2 the D-pad can be set to act as an actual D-pad (not analog stick) by pressing Up + Select (see the [8Bitdo FAQ](https://support.8bitdo.com/faq/zero2.html)). But then there is not proper configuration for this controller.

I've been messing around with controller.json, not knowing exactly how it works and what I was doing, but I got it to work.

I think it would be helpful if either the 8Bitdo Zero 2 could be added or if there were some documentation on how to add or modify a controller.

Some questions I had about controller.json:
* What's the difference between `buttons` and `axis_buttons`?
* What's the difference between `"8BitDo Zero (X Input)": {` and `"name": "8BitDo Zero (X Input)",`
* Are `axis_buttons` and `axes` required?

Here is what I changed in controller.json to get it to work for me:
```json
    "8BitDo Zero (X Input)": {
        "name": "8BitDo Zero (X Input)",
        "buttons": {
            "0": "B",
            "1": "A",
            "2": "Y",
            "3": "X",
            "4": "Left Shoulder",
            "5": "Right Shoulder",
            "8": "Select",
            "9": "Start",
            "14": "D-Pad Left",
            "15": "D-Pad Right",
            "12": "D-Pad Up",
            "13": "D-Pad Down"
        },
        "axis_buttons": {
            "99": "Menu"
        },
        "axes": {
            "98": "D-Pad Horizontal",
            "97": "D-Pad Vertical"
        },
        "num_buttons": 12,
        "num_axes": 2,
        "has_stick": false,
        "supported": true,
        "has_dpad": true
    },
```

**Comment by aguyfromsector2814** [comment]
I'm having this same issue but don't really know how to use JSON. Can you let me know how to make the changes that worked for you?

**Comment by roxgib** [comment]
At some point some changes were made to this controller's button and axis indexing, which the add-on has been updated to account for. I believe the change happened in Chromium, which would have then made its way to Anki via Qt6. From my testing the change appeared to be consistent across platforms, but perhaps I missed some configurations.

I've been trying to avoid different code for different platforms but it might be unavoidable in this case. Other options are to add more entries in the list of controllers to account for the differences, like there are X Mode and D Modes for this controller already, or add a page in the settings to allow users to customise how their controller is interpreted. I'll look at this today and see what the best way forward is. 

Thanks for reporting

**Comment by aguyfromsector2814** [comment]
> In the file controllers.json (Extras -> Addons -> Contanki -> Show files) I've replaced the section for 8BitDo Zero (X Input) with the above code (lines 527 to 554):
> 
> ```json
>     "8BitDo Zero (X Input)": {
>         ...
>     },
> ```
> 
> Set axis roles in Contanki options to unassigned and don't forget to put the D-pad in actual D-pad mode.

This worked for me, thank you so much! I did try to see if I could set the up and down buttons to scroll vertically, and that did not work. 

Wasn't even aware about resetting the D-pad and missed it in your original post, so thanks for mentioning that again.

**Comment by x51mon** [comment]
> I did try to see if I could set the up and down buttons to scroll vertically

I've created custom actions with <kbd>Page Up</kbd> and <kbd>Page Down</kbd> keys as shortcut and assigned those to buttons as a workaround.

**Comment by roxgib** [comment]
Thanks everyone for the input. I have just released a [new beta](https://github.com/roxgib/anki-contanki/releases/tag/v0.11-beta) that lets you reassign controls. Please give that a try and let me know if it addresses the issue. It won't be on AnkiWeb for a few days at least but can be downloaded from GitHub. 

This features also asks the user to share their configuration with me, which will hopefully make it easier to collect data on different controllers on different systems so they can be supported natively, but in the meantime it'll be easier for users to fix issues with control mappings without having to modify the data files. I really wanted controllers to just work out of the box but I probably should have added this earlier for when that isn't possible.

Just to answer a few questions that have been raised in this thread:
- References to the 8BitDo Zero in the add-on should also cover the 8BitDo Zero 2, which is what I've been testing with as I don't actually have an original Zero. It may be that the recent update means they now present differently, so I'm looking into acquiring an original Zero for testing. 
- The items 'buttons', 'axes', and 'axis_buttons' in `controllers.json` are, respectively, the names of the buttons, the names of the axes, and the names of the axes when used in in 'button mode'. They are mostly used for locating the icon for each button, but the recent update also uses these names for reassigning the controls.
- The numbers used with the axes are a little confusing because they sometimes have to coexist with the buttons indexes which overlap, and because there are two buttons for each axis (e.g. Stick Left and Stick Right). I'l look at adding some documentation around that, and in the long run the ints should really be replaced with a custom class.

> Are axis_buttons and axes required?

Yes, for getting the icons (and also just because the code expects them).

> On the Zero 2 the D-pad can be set to act as an actual D-pad (not analog stick) by pressing Up + Select (see the [8Bitdo FAQ](https://support.8bitdo.com/faq/zero2.html)). But then there is not proper configuration for this controller.

Good catch, that should hopefully be easier to support, but I'm wiped so I'll take a look at that tomorrow.

Thanks again everyone. I have a mountain of controllers that I test across Windows, Mac and Linux, but it's hard to catch everything and sometimes I'm just not able to reproduce the issue, so I really appreciate everyone's help. 

As for what's actually causing the Zero 2's d-pad not to work - I'm still not sure, other than the indices coming from the underlying API are not consistent for different users. I suspect a difference between Qt5 and Qt6 might also be causing issues for some people, but I really need to dig into the Chromium codebase to see what's going on.

**Comment by roxgib** [comment]
@x51mon Thanks for trying it. Do the button icons flash on the "Controls" tab when you press the corresponding button on the controller?

**Comment by x51mon** [comment]
No, nothing happens in the Controls tab either.

**Comment by x51mon** [comment]
The D-pad works right away now, in D-pad mode as well as when set to left analog stick. The part for Axis Roles in the Options tab is missing, not sure if that's intentional.

Unfortunately the buttons in the Controls tab are still not flashing.

**Comment by x51mon** [comment]
@aguyfromsector2814 You need to restart Anki after enabling the add-on. Connect a controller and press a button so it gets detected, then you should have an entry "Controller Options" in the Tools menu.

**Comment by aguyfromsector2814** [comment]
@x51mon Tried restarting and got the same thing. Just to make sure I am downloading the right thing, all I need is contanki.ankiaddon right? 
![image](https://github.com/roxgib/anki-contanki/assets/152656670/35bddb1b-4ef4-49bd-9b9a-121f4dcf4c6e)

**Comment by roxgib** [comment]
> The part for Axis Roles in the Options tab is missing, not sure if that's intentional.

Yes, they are now implemented as buttons, because that was easier. I'm not sure anyone was actually using them as a stick (to move the mouse around etc) because they're bad at the that, so buttons make more sense. Unfortunately in D-Input mode there weren't enough extra buttons to do that, and also the "D-Pad Mode" (Select + D-Pad Up) seems to be broken for me in D-Input mode, so they are still axes in D-Input Mode.

> Unfortunately the buttons in the Controls tab are still not flashing.

Yeah I still don't know what's causing that, going to try some things today.

>The D-pad works right away now, in D-pad mode as well as when set to left analog stick.

Excellent! It's a bit ironic that 8BitDo has added these different modes for maximum compatibility and now we're having to support all of them, but here we are.

I've also managed to acquire an original 8BitDo Zero, which I will now test along side the Zero 2. I tried it briefly yesterday but and didn't notice any differences.

**Comment by roxgib** [comment]
> I have no idea what I'm doing but I tried to download the beta to try it out but when I open up the add-on in Anki all I get is this

@aguyfromsector2814 Yes, you have downloaded the correct thing. I assume you're opening the main Anki add-on menu and clicking config or double clicking the add-on from the list? Seems like the add-on is not being initialised, so it's not registering the config dialog and Anki just opens the config file instead, which is the default if an add-on doesn't provide it's own config.

Make sure:
- you're on a recent version of Anki
- the add-on is enabled
- no other version of the add-on is enabled (e.g. the version on AnkiWeb vs a beta from here
- restart Anki once you've confirmed all the above

If that doesn't help please open a separate issue and I'll look into it further.

**Comment by aguyfromsector2814** [comment]
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.0-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-07 10:10:06

When loading Contanki - Controller Support:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/contanki/__init__.py", line 6, in <module>
    from .contanki import Contanki
  File "/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/contanki/contanki.py", line 14, in <module>
    from .quick import QuickSelectMenu
  File "/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/contanki/quick.py", line 16, in <module>
    from .icons import get_button_icon
  File "/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/contanki/icons.py", line 23, in <module>
    from .controller import Controller
  File "/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/contanki/controller.py", line 29, in <module>
    for c in get_controller_data().values()
  File "/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/contanki/controller.py", line 18, in get_controller_data
    for file in os.listdir(os.path.join(user_files_path, "custom_controllers")):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/aguyfromsector2814/Library/Application Support/Anki2/addons21/contanki/user_files/custom_controllers'

@roxgib No luck. I am on 23.10.1, deleted the other contanki add-on, and enabled the beta. Getting the debug info above on startup.

**Comment by roxgib** [comment]
@aguyfromsector2814 Ah dammit, I thought I'd fixed that. Oh well, we're now up to [Beta 21](https://github.com/roxgib/anki-contanki/releases/tag/v0.11.3-beta)

**Comment by x51mon** [comment]
> Yes, they are now implemented as buttons, because that was easier. I'm not sure anyone was actually using them as a stick (to move the mouse around etc) 

It would be nice to have an option for smooth scrolling. I've tried to set up custom actions with keyboard arrow keys but then you need to press the button repeatedly to continue scrolling. But maybe it's easy to add it as an option for the buttons? Otherwise don't bother, Page Up/Down is usable too.

**Comment by aguyfromsector2814** [comment]
I

> @aguyfromsector2814 Ah dammit, I thought I'd fixed that. Oh well, we're now up to [Beta 21](https://github.com/roxgib/anki-contanki/releases/tag/v0.11.3-beta)

I've been using it for the past few days and have no issues. Thanks for all the work you have put into this!

Agree that smooth scrolling would be nice but it is not a necessity.

**Comment by roxgib** [comment]
> It would be nice to have an option for smooth scrolling

Agreed. Currently the buttons are filtered to those where the state has changed well before the action is looked up, so would need a bit of work to make this happen, but if someone wants to open an issue I will get to it at some point.

> I've been using it for the past few days and have no issues.

Thanks for testing, Beta 21 is now on Ankiweb.

**Comment by x51mon** [comment]
> Currently the buttons are filtered to those where the state has changed well before the action is looked up, so would need a bit of work to make this happen

I think there is some misunderstanding here, want I meant to ask: is it easy to add a normal button action, that can be assigned to any button in the Controls tab, that does smooth scrolling?
E.g. repeatedly send Up/Down **while** a button on the controller is pressed, acting in a similar way to holding down the Up/Down keys on the keyboard. I don't know the internals of Contanki, but it seams to me that it might be simple thing to do.

**Comment by roxgib** [comment]
> is it easy to add a normal button action, that can be assigned to any button in the Controls tab, that does smooth scrolling?

What I was trying to say above was that actions are only triggered when a button changes from pressed to unpressed, or vice versa.  This is the relevant code:

https://github.com/roxgib/anki-contanki/blob/ec69ad3ed47ffdbed30f3ff35d2bf8639a2357a3/contanki/contanki.py#L203-L204

And then further down:

https://github.com/roxgib/anki-contanki/blob/ec69ad3ed47ffdbed30f3ff35d2bf8639a2357a3/contanki/contanki.py#L224-L225

The `do_action` method takes the index and looks up the assigned action, it's only at that point we'd know whether the action should be repeated as long as the button is held down, but buttons that are pressed but the action has already triggered don't reach that point on the next poll. So currently it's not trivial to add an action that triggers so long as the button is pressed. Obviously it's possible, I just want to be careful because the `poll` function touches so many things and there's a lot of potential for bugs and it would require a lot of testing.

Another way to do it would just be to start scrolling asynchronously until the button release is registered, I'll see if that's easier.

I'd also intended to move more of the polling logic into the JS so it wouldn't have to call the JS bridge every poll. Since both of those changes touch the same code I might try to do both over the coming holidays. This would also avoid duplicating the testing.

**Comment by x51mon** [comment]
Thanks for the detailed explanation. And no pressure, if you don't feel like doing it that's totally fine.
